name: adb_kit
description: The best ADB client for Android/Windows/Linux/macOS.
publish_to: "none"
version: 1.5.4+45
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  # localizations
  intl: ^0.19.0
  animations: ^2.0.2
  # # desktop window stype
  # flutter_acrylic: ^1.1.0
  # adb plugin can manager app
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  # network
  dio: ^5.4.3
  # file drop
  desktop_drop: ^0.4.1
  file_selector: ^0.8.4+2
  # get app local dir
  path_provider: ^2.0.10
  # responsive ui
  responsive_framework: ^1.0.0
  flutter:
    sdk: flutter
  # terminal widget
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
      ref: master
  # local pty
  flutter_pty: ^0.3.1
  # # color select
  # cyclop: ^0.5.2
  # some animations
  flutter_spinkit: "^4.1.2"
  # svg image
  flutter_svg: ^1.1.0
  # state manager...
  get: ^4.6.6
  # some foundation
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  # multicast on LAN
  multicast:
    git: https://github.com/nightmare-space/multicast
  file_manager_view:
    git: https://github.com/nightmare-space/file_manager_view.git
  # can receive mdns message
  multicast_dns: ^0.3.0
  # generate QR widget
  qr_flutter: ^4.0.0
  # scan qr code with camera
  qr_code_scanner: ^0.5.1
  path: ^1.8.0
  # launcher url
  url_launcher: ^6.0.18
  # adb command util
  adbutil:
    git: https://github.com/nightmare-space/adbutil
  # file selector,but developed by nightmare
  # adb plugin can launcher app
  # app_launcher:
  #   git: https://github.com/nightmare-space/app_launcher
  # foundation settings
  settings:
    git: https://github.com/nightmare-space/settings
  # adb plugin can view android device info and cpu/gpu status
  device_info:
    git: https://github.com/nightmare-space/device_info.git
  # can manage window on desktop
  window_manager: ^0.3.0
  flutter_markdown: ^0.6.10+2
  screenshot: ^3.0.0
  device_info_plus: ^10.1.0
  # 下面两个是非开源库，个人编译需要移除
  # 并手动解决编译报错
  termux_api_plugin:
    path: ../termux_api_plugin
  adb_kit_extension:
    path: ../adb_kit_extension
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/
    - CHANGELOG.md

dependency_overrides:
  flutter_spinkit: ^5.1.0
  visibility_detector: ^0.3.3
  ffi: 2.1.2
  flutter_svg: 1.1.5
  flutter_widget_from_html_core: ^0.14.6
  android_intent_plus: 4.0.1
  fl_chart: ^0.68.0
  win32_registry: 1.1.3
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart.git
      ref: master
  qr_code_scanner: ^1.0.0

flutter_intl:
  enabled: true
  localizely:
    project_id: 483edf0e-5f6c-489d-8b86-731bba09be1b
