name: adb_tool
description: 支持Android、macOS的adb工具，提供更方便的连接与设备操作.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.2+13
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  app_manager: 
    path: /Users/nightmare/Desktop/Server/app_manager
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_screenutil: ^2.3.0
  flutter_spinkit: "^4.1.2"
  # svg图像
  flutter_svg: ^0.22.0
  get: ^4.1.3
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  multicast:
    git: https://github.com/nightmare-space/multicast
  multicast_dns: ^0.3.0
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.5.1
  signale:
    git: https://github.com/Nightmare-MY/signale
  termare_pty:
    git: https://github.com/termare/termare_pty
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/android/
    - assets/icon/
    - assets/

dependency_overrides:
  dart_pty:
    path: /Users/nightmare/Desktop/termare-space/dart_pty

  global_repository:
    path: /Users/nightmare/Desktop/nightmare-space/global_repository
    # path: C:\Users\Nightmare\Documents\termare-space\dart_pty
