name: adb_tool
description: The best ADB client for Android/Windows/Linux/macOS.
publish_to: "none"
version: 1.3.3+30
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  animations: ^2.0.2
  flutter_acrylic: ^1.0.0
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  dio: ^4.0.0
  desktop_drop: ^0.3.3
  file_selector: ^0.8.2+1
  file_selector_linux: 0.0.2+1
  file_selector_macos: ^0.0.4+1
  file_selector_windows: ^0.0.2+1
  responsive_framework: ^0.1.7
  flutter:
    sdk: flutter
  cyclop: ^0.5.2
  flutter_screenutil: ^2.3.0
  flutter_spinkit: "^4.1.2"
  pseudo_terminal_utils:
    git: https://github.com/Termare/pseudo_terminal_utils
  flutter_svg: ^0.22.0
  get: ^4.1.3
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  multicast:
    git: https://github.com/nightmare-space/multicast
  multicast_dns: ^0.3.0
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.5.1
  path: ^1.8.0
  termare_pty:
    git: https://github.com/Termare/termare_pty
  url_launcher: ^6.0.18
  logger_view:
    git: https://github.com/nightmare-space/logger_view
  adbutil:
    git: https://github.com/nightmare-space/adbutil
  termare_view:
    git: https://github.com/Termare/termare_view
  file_selector_nightmare:
    git: https://github.com/nightmare-space/file_selector_meng
  app_launcher:
    git: https://github.com/nightmare-space/app_launcher
  settings:
    git: https://github.com/nightmare-space/settings
  device_info:
    git: https://github.com/nightmare-space/device_info.git
  window_manager: ^0.2.3
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/android/
    - assets/
    - CHANGELOG.md

dependency_overrides:
  # global_repository:
  #   path: ../global_repository
  # # app_launcher:
  # #   path: ../app_launcher
  # # multicast:
  # #   path: ../multicast
  get: 
    hosted: 
      name: get
      url: https://pub.dev
    version: ^4.6.3
  device_info:
    path: ../device_info
  app_manager:
    path: ../app_manager
  adbutil:
    path: ../adbutil
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  # file_selector_nightmare:
  #   path: ../file_selector_meng
flutter_intl:
  enabled: true
  localizely:
    project_id: 483edf0e-5f6c-489d-8b86-731bba09be1b
