name: adb_tool
description: 支持Android、macOS的adb工具，提供更方便的连接与设备操作.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.0+11
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  get: ^4.1.3
  qr_flutter: ^3.1.0
  dio: ^4.0.0
  signale:
    git: https://github.com/Nightmare-MY/signale
  flutter_screenutil: ^2.3.0
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  permission_handler: ^8.0.0+1
  qrscan: ^0.2.21
  termare_pty:
    git: https://github.com/termare/termare_pty
  # svg图像
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.4
  flutter_markdown: ^0.6.1
  multicast_dns: ^0.3.0
  multicast:
    git: https://github.com/nightmare-space/multicast

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/android/
    - assets/icon/
    - assets/README.md

dependency_overrides:
  dart_pty:
    path: /Users/nightmare/Desktop/termare-space/dart_pty
    # path: C:\Users\Nightmare\Documents\termare-space\dart_pty
