name: adb_tool
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.7+8
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_admob: ^0.8.0+1
  flutter_spinkit: "^4.1.2"
  get: ^4.1.3
  qr_flutter: ^3.1.0
  dio: ^3.0.3
  flutter_screenutil: ^2.3.0
  custom_log:
    git:
      url: https://github.com/nightmare-space/custom_log
      ref: dart
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  permission_handler: ^5.0.1+1
  qrscan: ^0.2.21
  termare_pty:
    git: https://github.com/termare/termare_pty
  # svg图像
  flutter_svg: 0.20.0-nullsafety.3
  url_launcher: ^5.7.10
  flutter_markdown: ^0.5.2
  nfc_in_flutter: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
  assets:
    - assets/android/
    - assets/icon/
    - assets/lib/
    - assets/README.md
